### ISSUE TITLE
Support for page url unmasking

### ISSUE THREAD

**Issue by aik099** [qa-tools/qa-tools#106]
The PageObject extension for Behat supports so called url unmasking (see https://github.com/sensiolabs/BehatPageObjectExtension/blob/master/src/SensioLabs/Behat/PageObjectExtension/PageObject/Page.php#L255).

Basically within url itself you have placeholders that will be replaced with given parameter values. Say page url is `/products/{type}.html` and we do this:

```php
$page = new ProductsPage($page_factory);
$page->open(array('type' => 'featured', 'test' => 'value'));
```

will produce this url: `/products/featured.html?test=value`.

More docs: http://behat-page-object-extension.readthedocs.org/en/latest/guide/working_with_page_objects.html#opening-a-page

**Comment by evangelion1204** [comment]
But wouldn't we break BC with this feature? Currently the params passed to `open` are query params. 

We can implement a new `Builder` which supports this new feature and keep the old as default
*OR*
The call could to look like 
```php 
$page->open(array('query' => array(...), 'replace' => array('type' => 'featured', 'test' => 'value')));
```
To keep BC we always wrap params in `query` as long as there is no `query` or `replace`.

**Comment by aik099** [comment]
If developer won't be using `{something}` in url, then nothing will be replaced. If he will, then I wonder what kind of website has such urls.

**Comment by slde-gorillaman** [comment]
Did anyone work on this already?

**Comment by aik099** [comment]
> But wouldn't we break BC with this feature? Currently the params passed to `open` are query params. 

@evangelion1204 , that would be a BC break only somebody already was using `{...}` in urls, which I doubt happened. I see this implemented like this:

* change `QATools\QATools\PageObject\Url\Builder::build` method only
* when a param `$params` array was found in URL itself in `{param_name}` notation, then:
 * replace it in url (can be multiple occurencies)
 * unset it from `$params` array so that it won't be added to query string

> Did anyone work on this already?

@slde-gorillaman , I see no associated PR. If you'd like to send one I would merge it. Don't forget about unit tests.
