### ISSUE TITLE
Don't use "SelectorsHandler::xpathLiteral" method 

### ISSUE THREAD

**Issue by aik099** [qa-tools/qa-tools#115]
The `SelectorsHandler::xpathLiteral` method will be deprecated in Mink 1.7 and the `Element::getSelectorsHandler` method, that is currently (in QA-Tools) used to reach selectors handler will be removed after https://github.com/minkphp/Mink/pull/641 merge.

We should use `Escaper::escapeLiteral` method, which (class & method) was introduced in Mink 1.6 to do xpath escaping when we're manually building xpaths.

**Comment by evangelion1204** [comment]
The `Escaper` can't be accessed (its private), in the `SeleniumSelector` I would create/pass an instance but I am not sure about `Select` and the others. We could provide an instance also there, which would be the easiest solution. Or we could also think about a custom selector handler. Like finding the options of a select.

**Comment by aik099** [comment]
Yes, with Escaper class you can't get it's instance from selectors handler or any other Mink part. That's why we have to create our Escaper instance and use it instead. Currently the selectors handler is stored in session and therefore Mink is doing `new Escaper()` only once. We should think of the way how we can do it too. Maybe we can store an instance in the PageFactory.

**Comment by evangelion1204** [comment]
> I don't remember if selectors handler concept wasn't removed from Mink after Escaper class was introduced.

The selectors are still there, I am not really sure if they help us.



> We should think of the way how we can do it too. Maybe we can store an instance in the PageFactory.

This might work out but only elements inheriting `AbstractElementContainer` are able to access the `PageFactory`but `Select` and `LabeledElement` are subclasses of `AbstractTypifiedElement` which never needed the PageFactory. 
The easiest way would to move the factory one level up to the Element or create it in classes that require an `Escaper`. There should never be a need to use a custom `Escaper`.
