### ISSUE TITLE
Missing `getPage` in `IPageFactory`

### ISSUE THREAD

**Issue by evangelion1204** [qa-tools/qa-tools#118]
The interface should also contain the function `getPage`.

**Comment by aik099** [comment]
The `IPageFactory` interface is an interesting topic in general. Yes we use it to typehint all over the library, but I doubt that somebody would want to implement absolutely different PageFactory just by implementing interface alone.

We can add method to current interface, but currently library itself isn't using it anywhere.

**Comment by evangelion1204** [comment]
This is true, I just used in the Behat Extension and got a warning that it is not existing. Which is correct after all.

**Comment by aik099** [comment]
I've created separate issue about `IPageFactory` interface removal: #120
