### ISSUE TITLE
Add method to check for page instance by locator

### ISSUE THREAD

**Issue by evangelion1204** [qa-tools/qa-tools#122]
To check if a given page is of name `Login Page` we need to implement a method in `Page` which uses the `PageLocator` of the `PageFactory` and resolves the class name of the given name.

**Comment by aik099** [comment]
This method will just prove, that given page name resolves to class name of current page object. It won't really look in the browser url to determine that user is really on that page.

Is change I mentioned:
* planned
* not planned

And if it's planned, then would this be part of this task or another task implementation?

**Comment by evangelion1204** [comment]
> This method will just prove, that given page name resolves to class name of current page object. It won't really look in the browser url to determine that user is really on that page.

Which is ok. It should just check for the given instance. As you suggested we need it for the upcoming example and I think its a nice addition.

**Comment by aik099** [comment]
OK.

**Comment by aik099** [comment]
Agreed to close in favor of #121, because page class comparison only can detect mistakes in PageObject class internals, which doesn't really prove anything in the tests, where page url comparison would be more useful.
