### ISSUE TITLE
Add support for port definition

### ISSUE THREAD

**Issue by evangelion1204** [qa-tools/qa-tools#127]
Currently it is not possible to add a port to the base url. Some users tend to run a specific html-server for example on port 8080 (default port of node `http-server`).

**Comment by aik099** [comment]
:+1: , I'm a port geek. I have different web servers with different PHP versions running on different ports.

**Comment by aik099** [comment]
While handling the ports we need to skip port adding to final url, even if it's given, for default ports (80 for `http://` and 443 for `https://` protocols).

**Comment by evangelion1204** [comment]
Sorry I don't get it. If a port was specified as base then we should always add it shouldn't we? I know that might be a problem with https, I am not even sure if its valid to say `http://test.tld:8081`. In that case the the port definition shouldn't be part of the url but more a separate option for http and https.

**Comment by aik099** [comment]
What I mean is that if we have: `secure => false, port => 80` then built page url won't contain `:80` in it because it's default port for `http` protocol. Same for 443 port and `secure => true`.

**Comment by aik099** [comment]
Try adding `:80` to any url and see, that web server will redirect you to same url without port. So if we need to compare 2 urls we need to account for such web server behavior.

**Comment by evangelion1204** [comment]
Ok now I got it :) in case we have the default values we will not add them, sorry for the confusion.

**Comment by evangelion1204** [comment]
Would you mind to put this into the 1.1 milestone? This is something which would be nice for an CI-System which runs the application on different ports or different Docker containers.

**Comment by aik099** [comment]
Sure. In any case the 1.1 can't be released until we're done with Behat extension, because most of changes in 1.1 are to be able to communicate with Behat properly.

**Comment by evangelion1204** [comment]
Ok
