### ISSUE TITLE
Make easier for people to get started

### ISSUE THREAD

**Issue by aik099** [qa-tools/qa-tools#135]
While attending PHPTek 2015 (http://tek.phparch.com/) hackaton I was introducing other developers to the library and I've found out, that it's very hard to get stared due farly complex setup process:

1. go to http://www.seleniumhq.org/ website
2. download the latest JAR file of the server (download page has bunch of other stuff and people are not aware of what needs to be downloaded)
3. run the `java -jar selenium-server-standalone-2.45.0.jar` command (explain that it won't stop because it's running a server on 4444 port to which Mink will connect)
4. create a new composer-based project
5. copy-paste in a `require` block from http://www.qa-tools.io website to `composer.json`
6. go to https://github.com/minkphp/MinkSelenium2Driver page to grab `require` part for `composer.json` as well
7. install the dependencies
8. copy-paste contents of 5 example files from http://www.qa-tools.io/examples/02-HtmlElements/ page
9. realize that examples doesn't work because:
- we're missing `$session->start()` and `$session->stop()`
- the developer might be using virtual machine and they need to specify machine where selenium server runs in Mink driver configuration
10. realize that people with no Mink background are really confused

__Solution__
1. create new `qa-tools/skeleton` repo or similar that would:
* have installation instructions on readme 
* contain all examples from website
* can be installed via `composer create-project qa-tools/skeleton` command
2. add explanatory comments to the example code
3. put a command used to create skeleton project on the website and in repo readme

// cc: @kendaop and @hackley2

**Comment by evangelion1204** [comment]
That sounds great :) I even think that there is a package wrapper for selenium server in composer available, we could also use this.

https://packagist.org/packages/netwing/selenium-server-standalone
or
https://packagist.org/packages/se/selenium-server-standalone

**Comment by aik099** [comment]
I wonder if we should be making standalone qa-tools demo or we should stick with PHPUnit-Mink + QA-Tools combined demo? I wonder who will be using QA-Tools just like that without any test runner wrapped around it.

**Comment by aik099** [comment]
> That sounds great :) I even think that there is a package wrapper for selenium server in composer available, we could also use this.
> 
> https://packagist.org/packages/netwing/selenium-server-standalone
> or
> https://packagist.org/packages/se/selenium-server-standalone

Nice find, but unfortunately I think people won't be running Selenium on same machine where PHP project is. For example I have PHP on a virtual machine and selenium server is running on the main computer (where virtual machine lives).

**Comment by evangelion1204** [comment]
> I wonder if we should be making standalone qa-tools demo or we should stick with PHPUnit-Mink + QA-Tools combined demo? I wonder who will be using QA-Tools just like that without any test runner wrapped around it.

You are right, most ppl will use a test runnter like PHPUnit, no idea if this is still to most common used one.

**Comment by slde-gorillaman** [comment]
There's also a shortcut for all those who have docker installed to have a Selenium Node up and running.
```bash
docker run -d -p 4444:4444 selenium/standalone-firefox
```

**Comment by aik099** [comment]
Actually I've created https://github.com/qa-tools/phpunit-example/ repo to address this problem some time ago and just forgot to close this issue.
