### ISSUE TITLE
Proxies does not work for properties

### ISSUE THREAD

**Issue by evangelion1204** [qa-tools/qa-tools#137]
Having an proxied element like
```php
class LoginPane extends AbstractElementContainer
{

	/**
	 * The e-mail.
	 *
	 * @var TextInput
	 * @find-by('id' => 'some-id')
	 */
	public $email;

}
```

And trying to access it by:

```php
$this->loginPane->email->click();
```

Will result in ` Notice: Undefined property: QATools\QATools\PageObject\Proxy\WebElementProxy::$email in ...`

We should also proxy the properties implementing `__get` and `__set`.

**Comment by aik099** [comment]
You massive DocBlock formatting issue in your example code. Can you please fix it and see it will work after that?

Ah, I was thinking that element containers would have all properties protected and have special access method to use them. But your case seems to valid as well.

Feel free to add `__get` and `__set` method to all proxy classes with corresponding tests.

**Comment by evangelion1204** [comment]
I just wrote it from scratch, it was no actual example ;) Yeah I will block me some time :smile:

**Comment by aik099** [comment]
I've formatted the PHP example of yours.
