### ISSUE TITLE
Impossible to specify sub-folder via "base_url" config setting

### ISSUE THREAD

**Issue by aik099** [qa-tools/qa-tools#141]
Here is the setup:

* `base_url` config setting: `http://www.website.tld/some/sub-folder`
* `page-url` annotation is: `@page-url('/SomePage/')`

When `$page->open()` method is called, then `http://www.website.tld` url is visited instead of `http://www.website.tld/some/sub-folder/SomePage/`.

This happens, because `QATools\QATools\PageObject\Url\Parser::merge` method is just replacing components of parsed `base_url` with ones from `@page-url`. So if following components are defined in both urls, then later wins:

* `path`
* `query`

I propose to:

* concatenate `path` (string) of `base_url` and `@page-url` together
* merge `query` (array) from `path` of `base_url` and `@page-url` together

**Comment by aik099** [comment]
@evangelion1204 , any opinion about this? Sounds like a bug to you as well or you're actually want described behavior to stay?

**Comment by evangelion1204** [comment]
The proposal sounds correct.
I never thought about to using a path in my base url. But in this case it makes sense to concatenate base url and the defined path in the annotation.
