### ISSUE TITLE
qa-tools/phpunit-extension not working with PHPUnit 6.x

### ISSUE THREAD

**Issue by josh-palan** [qa-tools/qa-tools#197]
After installing both qa-tools and the phpunit-extension, I had my test classes extend \QATools\PHPUnitExtension\AbstractQAToolsTestCase, however, I am getting errors about PHPUnit_Framework_TestCase not found:

```
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /var/www/html/vendor/aik099/phpunit-mink/library/aik099/PHPUnit/BrowserTestCase.php on line 33

```

Am I missing something? Changing 

`abstract class BrowserTestCase extends \PHPUnit_Framework_TestCase implements IEventDispatcherAware`

to

`abstract class BrowserTestCase extends \PHPUnit\Framework\TestCase implements IEventDispatcherAware`

Seems to fix it for at least that class. It seems like there is an issue with namespacing, but I'm not sure if this is due to composer, or just that qa-tools phpunit-extension needs to be updated.

**Comment by aik099** [comment]
The `BrowserTestCase` class is part of https://github.com/minkphp/phpunit-mink/ project, not this one. Therefore issue must be reported in there.

I've reported issue in https://github.com/minkphp/phpunit-mink/issues/93 on your behalf. You're welcome to send PR and I'll make a release straight away.

**Comment by aik099** [comment]
Closing, because the connected issue in the PHPUnit-Mink project is now solved.
